export DIR=$BATS_TEST_DIRNAME
export BASE_DIR=$DIR/../
export DOCKER_HOST=tcp://0.0.0.0:2375
export OW_LOCAL_DOCKER_NW_NAME=owl
export TOTAL_CAPACITY=5
export DELEGATE_ON_FAILURE=true
export RETRIES=0
