export DIR=$BATS_TEST_DIRNAME
export BASE_DIR=$DIR/../
export DOCKER_HOST=tcp://0.0.0.0:2375
export OWL_NET_NAME=owl
export OWL_HOST_CAPACITY=5
export OWL_DELEGATE_ON_FAILURE=true
export OWL_RETRIES_NUMBER=0
